// ひらがな（清音46＋濁音・半濁音25＝71字）
// スキーマ: [かな, ローマ字, 例語, 例語のローマ字, 英語]
// ローマ字は src/romaji.js の変換器で検算する（ビルド時に全件チェック）。
export const KANA_A = [
["あ","a","あめ","ame","rain"],
["い","i","いぬ","inu","dog"],
["う","u","うみ","umi","sea"],
["え","e","えき","eki","station"],
["お","o","おかね","okane","money"],
["か","ka","かさ","kasa","umbrella"],
["き","ki","きって","kitte","postage stamp"],
["く","ku","くつ","kutsu","shoes"],
["け","ke","けさ","kesa","this morning"],
["こ","ko","こえ","koe","voice"],
["さ","sa","さかな","sakana","fish"],
["し","shi","しお","shio","salt"],
["す","su","すし","sushi","sushi"],
["せ","se","せかい","sekai","world"],
["そ","so","そら","sora","sky"],
["た","ta","たまご","tamago","egg"],
["ち","chi","ちず","chizu","map"],
["つ","tsu","つくえ","tsukue","desk"],
["て","te","てがみ","tegami","letter"],
["と","to","とり","tori","bird"],
["な","na","なつ","natsu","summer"],
["に","ni","にく","niku","meat"],
["ぬ","nu","ぬの","nuno","cloth"],
["ね","ne","ねこ","neko","cat"],
["の","no","のみもの","nomimono","drink"],
["は","ha","はな","hana","flower"],
["ひ","hi","ひと","hito","person"],
["ふ","fu","ふゆ","fuyu","winter"],
["へ","he","へや","heya","room"],
["ほ","ho","ほん","hon","book"],
["ま","ma","まど","mado","window"],
["み","mi","みず","mizu","water"],
["む","mu","むし","mushi","insect"],
["め","me","めがね","megane","glasses"],
["も","mo","もり","mori","forest"],
["や","ya","やま","yama","mountain"],
["ゆ","yu","ゆき","yuki","snow"],
["よ","yo","よる","yoru","night"],
["ら","ra","らいねん","rainen","next year"],
["り","ri","りゆう","riyuu","reason"],
["る","ru","るす","rusu","not at home"],
["れ","re","れきし","rekishi","history"],
["ろ","ro","ろく","roku","six"],
["わ","wa","わたし","watashi","I; me"],
["を","o","ほんを","hon'o","(marks the object)"],
["ん","n","にほん","nihon","Japan"],
["が","ga","がっこう","gakkou","school"],
["ぎ","gi","ぎんこう","ginkou","bank"],
["ぐ","gu","ぐあい","guai","condition"],
["げ","ge","げんき","genki","healthy; lively"],
["ご","go","ごはん","gohan","rice; meal"],
["ざ","za","ざっし","zasshi","magazine"],
["じ","ji","じかん","jikan","time"],
["ず","zu","ずっと","zutto","all the time"],
["ぜ","ze","ぜんぶ","zenbu","all"],
["ぞ","zo","ぞう","zou","elephant"],
["だ","da","だいがく","daigaku","university"],
["ぢ","ji","はなぢ","hanaji","nosebleed"],
["づ","zu","つづく","tsuzuku","to continue"],
["で","de","でんわ","denwa","telephone"],
["ど","do","どようび","doyoubi","Saturday"],
["ば","ba","ばん","ban","evening"],
["び","bi","びょういん","byouin","hospital"],
["ぶ","bu","ぶんぽう","bunpou","grammar"],
["べ","be","べんきょう","benkyou","study"],
["ぼ","bo","ぼうし","boushi","hat"],
["ぱ","pa","いっぱい","ippai","full; a lot"],
["ぴ","pi","ぴかぴか","pikapika","sparkling"],
["ぷ","pu","てんぷら","tenpura","tempura"],
["ぺ","pe","ぺこぺこ","pekopeko","very hungry"],
["ぽ","po","さんぽ","sanpo","a walk"]
];
