// カタカナ（清音45＋濁音・半濁音23＝68字）
// スキーマ: [かな, ローマ字, 例語, 例語のローマ字, 英語]
// ヲ・ヂ・ヅ は現代のカタカナ表記ではまず使わないので入れていない。
// ひらがな側（kana-a.js）には ぢ・づ を入れてある（はなぢ・つづく）。
export const KANA_B = [
["ア","a","アイス","aisu","ice cream"],
["イ","i","インク","inku","ink"],
["ウ","u","ウール","uuru","wool"],
["エ","e","エアコン","eakon","air conditioner"],
["オ","o","オレンジ","orenji","orange"],
["カ","ka","カメラ","kamera","camera"],
["キ","ki","キロ","kiro","kilo"],
["ク","ku","クラス","kurasu","class"],
["ケ","ke","ケーキ","keeki","cake"],
["コ","ko","コーヒー","koohii","coffee"],
["サ","sa","サッカー","sakkaa","soccer"],
["シ","shi","シャツ","shatsu","shirt"],
["ス","su","スープ","suupu","soup"],
["セ","se","セーター","seetaa","sweater"],
["ソ","so","ソファ","sofa","sofa"],
["タ","ta","タオル","taoru","towel"],
["チ","chi","チケット","chiketto","ticket"],
["ツ","tsu","ツアー","tsuaa","tour"],
["テ","te","テレビ","terebi","television"],
["ト","to","トイレ","toire","toilet"],
["ナ","na","ナイフ","naifu","knife"],
["ニ","ni","ニュース","nyuusu","news"],
["ヌ","nu","ヌードル","nuudoru","noodles"],
["ネ","ne","ネクタイ","nekutai","necktie"],
["ノ","no","ノート","nooto","notebook"],
["ハ","ha","ハンカチ","hankachi","handkerchief"],
["ヒ","hi","ヒーター","hiitaa","heater"],
["フ","fu","フォーク","fooku","fork"],
["ヘ","he","ヘルメット","herumetto","helmet"],
["ホ","ho","ホテル","hoteru","hotel"],
["マ","ma","マッチ","matchi","match (fire)"],
["ミ","mi","ミルク","miruku","milk"],
["ム","mu","ムービー","muubii","movie"],
["メ","me","メール","meeru","email"],
["モ","mo","モデル","moderu","model"],
["ヤ","ya","タイヤ","taiya","tire"],
["ユ","yu","ユーモア","yuumoa","humor"],
["ヨ","yo","ヨーグルト","yooguruto","yogurt"],
["ラ","ra","ラジオ","rajio","radio"],
["リ","ri","リボン","ribon","ribbon"],
["ル","ru","ルール","ruuru","rule"],
["レ","re","レストラン","resutoran","restaurant"],
["ロ","ro","ロボット","robotto","robot"],
["ワ","wa","ワイン","wain","wine"],
["ン","n","パン","pan","bread"],
["ガ","ga","ガラス","garasu","glass (material)"],
["ギ","gi","ギター","gitaa","guitar"],
["グ","gu","グラス","gurasu","drinking glass"],
["ゲ","ge","ゲーム","geemu","game"],
["ゴ","go","ゴム","gomu","rubber"],
["ザ","za","ピザ","piza","pizza"],
["ジ","ji","ジュース","juusu","juice"],
["ズ","zu","サイズ","saizu","size"],
["ゼ","ze","ゼロ","zero","zero"],
["ゾ","zo","ゾーン","zoon","zone"],
["ダ","da","ダンス","dansu","dance"],
["デ","de","デパート","depaato","department store"],
["ド","do","ドア","doa","door"],
["バ","ba","バス","basu","bus"],
["ビ","bi","ビール","biiru","beer"],
["ブ","bu","ブラシ","burashi","brush"],
["ベ","be","ベッド","beddo","bed"],
["ボ","bo","ボタン","botan","button"],
["パ","pa","パソコン","pasokon","computer"],
["ピ","pi","ピアノ","piano","piano"],
["プ","pu","プール","puuru","swimming pool"],
["ペ","pe","ペン","pen","pen"],
["ポ","po","ポスト","posuto","mailbox"]
];
