// 敵キャラのドット絵データ（すべてオリジナル）
// px: 12行×12文字。'.' は透明、その他の文字は pal のキー
// area: どのダンジョンに出るか（vocab / kanji / grammar / any / boss）
export const MONSTERS = [
  {
    id: 'kotonoha', name: 'ことのはガ', en: 'Wordwing', area: 'vocab', hp: 3,
    msg: 'ひらひらと ことばを まきちらしている。',
    pal: { a: '#3E8E4A', b: '#6FCE6A', c: '#BFF07A', d: '#14240F' },
    px: [
      '.......daad..daad.......',
      '......daaad..daaad......',
      '.....ddaaad..daaadd.....',
      '....daaaaaddddaaaaad....',
      '...ddaaaabbbbbbaaaadd...',
      '..daaaabbbbbbbbbbaaaad..',
      '..daaaabbbbccbbbbaaaad..',
      '.daaabbbbccccccbbbbaaad.',
      '.daaabbbbccccccbbbbaaad.',
      'daaabbbbccccccccbbbbaaad',
      'daaabbbbccccccccbbbbaaad',
      'aaaabbbbccccccccbbbbaaaa',
      'aaaabbbbccddddccbbbbaaaa',
      'daaabbbbccddddccbbbbaaad',
      'daaabbbbccccccccbbbbaaad',
      '.ddaabbbbccccccbbbbaadd.',
      '..daabbbbccccccbbbbaad..',
      '...ddaabbbbccbbbbaadd...',
      '....daaaabbbbbbaaaad....',
      '.....ddaaabbbbaaadd.....',
      '......daaaddddaaad......',
      '.......daad..daad.......',
      '........dd....dd........',
      '........................'
  ]
  },
  {
    id: 'goiworm', name: 'ゴイワーム', en: 'Lexiworm', area: 'vocab', hp: 4,
    msg: 'ずかんの ページを かじって そだった。',
    pal: { a: '#7A4E9E', b: '#B47FD8', c: '#E4C6F5', d: '#18102A' },
    px: [
      '.........ddbbbbdd.......',
      '........dbbbbbbbbd......',
      '........dbbccccbbd......',
      '.......dbbccccccbbd.....',
      '.......dbbccddccbbd.....',
      '.......dbbccddccbbd.....',
      '.......dbbccccccbbd.....',
      '........dbbccccbbd......',
      '........dbbbbbbbbd......',
      '.........dbbbbbbd.......',
      '.......ddaaaaaaaadd.....',
      '......daaaaaaaaaaaad....',
      '.....ddaaaabbbbaaaadd...',
      '....daaaabbbbbbbbaaaad..',
      '...ddaaaabbbbbbbbaaaadd.',
      '..daaaabbbbbbbbbbbbaaaad',
      '..daaaabbbbbbbbbbbbaaaad',
      '.daaaabbbbbbbbbbbbbbaaaa',
      '.daaaabbbbbbbbbbbbbbaaaa',
      '..daaaabbbbbbbbbbbbaaaad',
      '..daaaaaabbbbbbbbaaaaaad',
      '...ddaaaaaabbbbaaaaaadd.',
      '.....ddaaaaaaaaaaaadd...',
      '.......ddaaaaaaaadd.....'
  ]
  },
  {
    id: 'fudeobake', name: 'ふでおばけ', en: 'Brushwraith', area: 'kanji', hp: 3,
    msg: 'すみを たらしながら ういている。',
    pal: { d: '#14142A', a: '#8B5A2B', b: '#C89050', c: '#1C1C2E', e: '#F0E060' },
    px: [
      '..........daad..........',
      '.........daaaad.........',
      '.........daaaad.........',
      '........daaaaaad........',
      '........daabbaad........',
      '.......daabbbbaad.......',
      '.......daabbbbaad.......',
      '......daabbbbbbaad......',
      '......daabbbbbbaad......',
      '.....daabbbbbbbbaad.....',
      '.....daabbbbbbbbaad.....',
      '....daaabbbbbbbbaaad....',
      '....daaccccccccccaad....',
      '...daccccccccccccccad...',
      '...dcccceecccceeccccd...',
      '...dcccceecccceeccccd...',
      '...dccccccccccccccccd...',
      '....dccccccccccccccd....',
      '....dccccccccccccccd....',
      '.....ddccccccccccdd.....',
      '......dccccccccccd......',
      '.......ddccccccdd.......',
      '........dccccccd........',
      '.........ddccdd.........'
  ]
  },
  {
    id: 'kanjigolem', name: 'カンジゴーレム', en: 'Glyph Golem', area: 'kanji', hp: 5,
    msg: 'からだが すべて へんと つくりで できている。',
    pal: { a: '#5A6472', b: '#8C97A8', c: '#D2DAE6', d: '#E8603A' },
    px: [
      '...ddaaaaaaaaaaaaaadd...',
      '..daaaaaaaaaaaaaaaaaad..',
      '..daabbbbbbbbbbbbbbaad..',
      '.daabbbbbbbbbbbbbbbbaad.',
      '.daabbccbbbbbbbbccbbaad.',
      '.daabbccbbbbbbbbccbbaad.',
      '.daabbddbbbbbbbbddbbaad.',
      '.daabbddbbbbbbbbddbbaad.',
      '.daabbbbbbccccbbbbbbaad.',
      '.daabbbbbbccccbbbbbbaad.',
      '.daabbbbbbbbbbbbbbbbaad.',
      '..daabbbbbbbbbbbbbbaad..',
      '...daaabbbbbbbbbbaaad...',
      '.dddaaaabbbbbbbbaaaaddd.',
      'daaaaaaabbbbbbbbaaaaaaad',
      'aaaaaaaaabbbbbbaaaaaaaaa',
      'aabbbbaaaabbbbaaaabbbbaa',
      'aabbbbaaaabbbbaaaabbbbaa',
      'aaaaaaaabbbbbbbbaaaaaaaa',
      'daaaaaaabbbbbbbbaaaaaaad',
      '.dddddaaaaddddaaaaddddd.',
      '....ddaaaad..daaaadd....',
      '...daaaaaad..daaaaaad...',
      '...daaaaad....daaaaad...'
  ]
  },
  {
    id: 'bunporobo', name: 'ブンポウロボ', en: 'Grammatron', area: 'grammar', hp: 4,
    msg: 'せつぞくの きそくを まもらせようとしてくる。',
    pal: { d: '#14142A', a: '#33528C', b: '#7CA6E0', c: '#FF5A4A' },
    px: [
      '.....ddaaaaaaaaaadd.....',
      '....daaaaaaaaaaaaaad....',
      '....daabbbbbbbbbbaad....',
      '...daabbbbbbbbbbbbaad...',
      '...daabbccbbbbccbbaad...',
      '...daabbccbbbbccbbaad...',
      '...daabbbbbbbbbbbbaad...',
      '...daabbbbbbbbbbbbaad...',
      '...daabbbbbccbbbbbaad...',
      '....daabbbccccbbbaad....',
      '.....daaaaaaaaaaaad.....',
      '.....daaaaaaaaaaaad.....',
      '...ddaaaaaaaaaaaaaadd...',
      '..daaaaaaaaaaaaaaaaaad..',
      '..dabbaaaaaaaaaaaabbad..',
      '.daabbaaaaaaaaaaaabbaad.',
      '.daabbaaaaaaaaaaaabbaad.',
      '..dabbaaaaaaaaaaaabbad..',
      '..daaaaaaaaaaaaaaaaaad..',
      '...ddaaaaaaaaaaaaaadd...',
      '.....daaaaaddaaaaad.....',
      '....ddaaaad..daaaadd....',
      '...daaaaaad..daaaaaad...',
      '...daaaaad....daaaaad...'
  ]
  },
  {
    id: 'jokenryu', name: 'ジョウケンリュウ', en: 'Condragon', area: 'grammar', hp: 5,
    msg: 'じょうけんを みたさないと とおしてくれない。',
    pal: { a: '#1E6E5E', b: '#37A88E', c: '#8FE0CC', d: '#F8D048' },
    px: [
      '....daad........daad....',
      '...daaaad......daaaad...',
      '...daaaad......daaaad...',
      '..daaaaaaddddddaaaaaad..',
      '..daaaaaaaaaaaaaaaaaad..',
      '.daaaaaaaaaaaaaaaaaaaad.',
      '.daaabbbbbbbbbbbbbbaaad.',
      '.daabbbbbbbbbbbbbbbbaad.',
      '.daabbddbbbbbbbbddbbaad.',
      '.daabbddbbbbbbbbddbbaad.',
      '.daabbbbbbbbbbbbbbbbaad.',
      '.daaabbbbbbbbbbbbbbaaad.',
      '.daaabbbbbbbbbbbbbbaaad.',
      '..daaabbbbbbbbbbbbaaad..',
      '..daaaccccccccccccaaad..',
      '...daacccccccccccacad...',
      '...daaccaaccaaccaaccd...',
      '...daaccaaccaaccaaccd...',
      '...daacccccccccccccad...',
      '....daacccccccccccad....',
      '....daaaaaaaaaaaaaad....',
      '.....ddaaaaaaaaaadd.....',
      '......daaaaddaaaad......',
      '.......daad..daad.......'
  ]
  },
  {
    id: 'machigai', name: 'マチガイドクロ', en: 'Blunderskull', area: 'any', hp: 4,
    msg: 'にどめの まちがいを まちかまえている。',
    pal: { d: '#14142A', a: '#E8E4D8', b: '#20202E' },
    px: [
      '.....ddaaaaaaaaaadd.....',
      '....daaaaaaaaaaaaaad....',
      '...ddaaaaaaaaaaaaaadd...',
      '..daaaaaaaaaaaaaaaaaad..',
      '..daaaaaaaaaaaaaaaaaad..',
      '.daaaaaaaaaaaaaaaaaaaad.',
      '.daaaaabbaaaaaabbaaaaad.',
      '.daaaabbbbaaaabbbbaaaad.',
      '.daaaabbbbaaaabbbbaaaad.',
      '.daaaaabbaaaaaabbaaaaad.',
      '.daaaaaaaaaaaaaaaaaaaad.',
      '..daaaaaaaaaaaaaaaaaad..',
      '..daaaaaaabbbbaaaaaaad..',
      '...ddaaaaabbbbaaaaadd...',
      '.....daaaaaaaaaaaaad....',
      '....dddaaaaaaaaaaad.....',
      '...daaddaaddaaddaad.....',
      '...daaddaaddaaddaad.....',
      '...daaaaaaaaaaaaaad.....',
      '...daaaaaaaaaaaaaad.....',
      '...daaddaaddaaddaad.....',
      '...daaddaaddaaddaad.....',
      '....dd..dd..dd..dd......',
      '........................'
  ]
  },
  {
    id: 'wasureme', name: 'ワスレメダマ', en: 'Forgeteye', area: 'any', hp: 3,
    msg: 'みつめていると おぼえたことを わすれそうになる。',
    pal: { a: '#3A2E6E', b: '#6B58C4', c: '#FFFFFF', d: '#1A1020' },
    px: [
      '.......ddaaaaaadd.......',
      '.....ddaaaaaaaaaadd.....',
      '...ddaaaabbbbbbaaaadd...',
      '..daaaabbbbbbbbbbaaaad..',
      '..daabbbbccccccbbbbaadd.',
      '.daabbbccccccccccbbbbaad',
      '.daabbbccccccccccccbbaad',
      'daabbbccccccccccccccbbba',
      'daabbbcccccccddcccccbbbb',
      'aabbbbccccccddddccccbbbb',
      'aabbbbccccccddddccccbbbb',
      'aabbbbcccccccddccccccbbb',
      'aabbbbcccccccccccccccbbb',
      'daabbbbcccccccccccccccbd',
      'daabbbbccccccccccbbbaad.',
      '.ddaabbbbccccccbbbbaad..',
      '..daaaabbbbbbbbbbaaaad..',
      '...ddaaabbbbbbbbaaadd...',
      '.....daaddaaaaddaaad....',
      '....ddaad.daaaddaad.dd..',
      '...daaad..daaad.dd.daad.',
      '..daaad....daad....daaad',
      '.daaad.....daad.....daaa',
      '.daad......daad......daa'
  ]
  },
  {
    id: 'goukaku', name: 'ゴウカクノツカイ', en: 'Herald of Passing', area: 'boss', hp: 10,
    msg: 'ごうかくの しるしを もって まちうけている。',
    pal: { a: '#C8A030', b: '#F0D878', c: '#FFFFFF', d: '#3A2E10' },
    px: [
      '.......ddaaaaaadd.......',
      '......daaaaaaaaaad......',
      '.....ddaabbbbbbaadd.....',
      '....daabbbbbbbbbbaad....',
      '....daabbbbccbbbbaad....',
      '...daabbbccccccbbbaad...',
      '...daabbccddddccbbaad...',
      '...daabbccddddccbbaad...',
      '...daabbbccccccbbbaad...',
      '....daabbbbccbbbbaad....',
      '.....dabbbbbbbbbbad.....',
      '...dddaabbbbbbbbaaddd...',
      '.ddaaaaabbbbbbbbaaaaadd.',
      'daaaaaabbbbbbbbbbaaaaaad',
      'aaaabbbbbbbbbbbbbbbbaaaa',
      'aaaabbbbbbbbbbbbbbbbaaaa',
      'daaaabbbbbbbbbbbbbbaaaad',
      '.ddaaaabbbbbbbbbbaaaadd.',
      '..daaaabbbbbbbbbbaaaad..',
      '...ddaaaabbbbbbaaaadd...',
      '.....daaaaddddaaaad.....',
      '....ddaaad....daaadd....',
      '...daaaaad....daaaaad...',
      '...daaadd......ddaaad...'
  ]
  }
];
