// 敵キャラのドット絵 その2（すべてオリジナル）
// 形式は monsters.js と同じ。12行×12文字、'.' は透明
export const MONSTERS_B = [
  // ---- 語彙の森 ----
  {
    id: 'ruigigoke', name: 'ソックリゴケ', en: 'Mimicmoss', area: 'vocab', hp: 3,
    msg: 'にた いみの ことばに ばけて ふえていく。',
    pal: { a: '#5E6B22', b: '#8EA83A', c: '#C8D46A', d: '#1E2210' },
    px: [
      '.......ddaaaaaadd.......',
      '.....ddaaaaaaaaaadd.....',
      '...ddaaaabbbbbbaaaadd...',
      '..daaaabbbbbbbbbbaaaad..',
      '.ddaabbbbccccccbbbbaadd.',
      'daabbbbccccccccccbbbbaad',
      'daabbbbcddccccddcbbbbaad',
      'aabbbbccddccccddcccbbbaa',
      'aabbbbccccccccccccccbbaa',
      'aabbbbccccccccccccccbbaa',
      'aabbbbcccccccccccccbbbaa',
      'daabbbbccccccccccbbbbaad',
      'daabbbbccccccccccbbbbaad',
      '.ddaabbbbccccccbbbbaadd.',
      '...dabbbbccccccbbbbad...',
      '...daabbbbbccbbbbbaad...',
      '.ddaaabbbbbbbbbbbbaaadd.',
      'daaaabbbbbbbbbbbbbbaaaad',
      'daaaabbbbbbbbbbbbbbaaaad',
      'aaaabbbbbbbbbbbbbbbbaaaa',
      'aaaaddaaaaaaaaaaaaddaaaa',
      'daaad.daaaaaaaaaad.daaad',
      'daaad.daaaaddaaaad.daaad',
      '.daad..daad..daad..daad.'
  ]
  },
  {
    id: 'katakanabachi', name: 'カタカナバチ', en: 'Katakanabee', area: 'vocab', hp: 4,
    msg: 'カタカナの ことばを あつめる はち。',
    pal: { a: '#C8A02A', b: '#2A2418', c: '#9EC8E0', d: '#E85A2A' },
    px: [
      '.....ddaaaaaaaaaadd.....',
      '....daaaaaaaaaaaaaaddd..',
      '...daaddddaaaaddddaaaad.',
      '...daaddddaaaaddddaaaad.',
      '....daaaaaaaaaaaaaaddd..',
      '.dd..ddaaaaaaaaaadd..dd.',
      'dccdd.daaaaaaaaaad.ddccd',
      'cccccd.daaaaaaaad.dccccc',
      'ccccccddaaaaaaaaddcccccc',
      'ccccccddaaaaaaaaddcccccc',
      'cccccd.dbbbbbbbbd.dccccc',
      'dccdd..dbbbbbbbbd..ddccd',
      '.dd...daaaaaaaaaad...dd.',
      '.....daaaaaaaaaaaad.....',
      '.....dbbbbbbbbbbbbd.....',
      '.....dbbbbbbbbbbbbd.....',
      '.....daaaaaaaaaaaad.....',
      '.....daaaaaaaaaaaad.....',
      '.....dbbbbbbbbbbbbd.....',
      '......dbbbbbbbbbbd......',
      '.......daaaaaaaad.......',
      '........daaaaaad........',
      '.........dbbbbd.........',
      '..........dbbd..........'
  ]
  },
  // ---- 漢字の遺跡 ----
  {
    id: 'bushuhebi', name: 'ブシュヘビ', en: 'Radiconda', area: 'kanji', hp: 4,
    msg: 'かんじの ぶひんに わかれて、また まきつく。',
    pal: { a: '#2E6B4A', b: '#4FA86E', c: '#C8E8A0', d: '#F0D030' },
    px: [
      '...........ddaaaadd.....',
      '..........daaaaaaaad....',
      '..........daabbbbaad....',
      '.........daabbbbbbaad...',
      '.........daaddbbddaad...',
      '.........daaddbbddaad...',
      '.........daabbbbbbaad...',
      '........daabbbbbbaad....',
      '.......ddaabbbbbbaad....',
      '......daabbbbbbaadd.....',
      '.....ddaabbbbbbaad......',
      '....daabbbbbbaadd.......',
      '....daabbbbbbaad........',
      '...daabbbbbbaad.........',
      '...daabbbbbbaad.........',
      '....daabbbbbbaad........',
      '....daabbbbbbaad........',
      '.....ddaabbbbbaaddd.....',
      '......daabbbccccbbadd...',
      '.......ddaabcccccbbaad..',
      '........daabbccccbbaad..',
      '.........ddaabbccccbbad.',
      '..........daabbccccbbbd.',
      '...........ddabbccccbd..'
  ]
  },
  {
    id: 'jukugogani', name: 'ジュクゴガニ', en: 'Combocrab', area: 'kanji', hp: 5,
    msg: 'ふたつの はさみで かんじを くみあわせる。',
    pal: { a: '#A83A2A', b: '#E06A4A', c: '#F8C8A0', d: '#2A1810' },
    px: [
      'daad................daad',
      'aaaaddd..........dddaaaa',
      'aaabbbad........dabbbaaa',
      'aabbbbaad......daabbbbaa',
      'aabbbbaad......daabbbbaa',
      'daabbaad........daabbaad',
      'daaaaaad........daaaaaad',
      '.ddaaad..dddddd..daaadd.',
      '..daaad.daaaaaad.daaad..',
      '...daaddaaaaaaaaddaad...',
      '...daaaaabbbbbbaaaaad...',
      '..daaaabbbbbbbbbbaaaad..',
      '.ddaabbbddbbbbddbbbaadd.',
      'daabbbbbddbbbbddbbbbbaad',
      'daabbbbbbbbbbbbbbbbbbaad',
      'aabbbbbbbbbbbbbbbbbbbbaa',
      'aabbbbccccccccccccbbbbaa',
      'daabbbccccccccccccbbbaad',
      'daabbbbbbbbbbbbbbbbbbaad',
      '.ddaabbbbbbbbbbbbbbaadd.',
      '...daaaaaaaaaaaaaaaad...',
      '..dddaaaaaaaaaaaaaaddd..',
      '.daaaddaaaaddaaaaddaaad.',
      '.daad..daad..daad..daad.'
  ]
  },
  // ---- 文法の塔 ----
  {
    id: 'joshikurage', name: 'ジョシクラゲ', en: 'Partijelly', area: 'grammar', hp: 3,
    msg: '「は」と「が」の あいだを ただよっている。',
    pal: { a: '#5A3A8E', b: '#8E6ACE', c: '#D8C8F0', d: '#F8D048' },
    px: [
      '.....ddaaaaaaaaaadd.....',
      '...ddaaaaaaaaaaaaaadd...',
      '.ddaaaabbbbbbbbbbaaaadd.',
      'daaaabbbbbbbbbbbbbbaaaad',
      'daabbbbccccccccccbbbbaad',
      'aabbbcccccccccccccbbbbaa',
      'aabbccddccccccddccbbbbaa',
      'aabbccddccccccddccbbbbaa',
      'aabbbcccccccccccccbbbbaa',
      'daabbbbccccccccccbbbbaad',
      'daabbbbbbbbbbbbbbbbbbaad',
      '.ddaabbbbbbbbbbbbbbaadd.',
      '...daaabbbbbbbbbbaaad...',
      '..dddaaabbbbbbbbaaaddd..',
      '.daaddaaddaaaaddaaddaad.',
      '.daaddaad.daaaddaaddaad.',
      '.dbbddbbd..dbbbddd.dbbd.',
      '.dbbddbbbd..dbbbd.dbbbd.',
      '..ddbbddbbd.dbbbddbbdd..',
      '..ddbbddbbd..dbbddbbdd..',
      '.dbbdd.dbbd...dbbbddbbd.',
      '.dbbdd.dbbbd...dbbddbbd.',
      '..dbbbd.dbbbd...dbbbbd..',
      '...dbbd..dbbd....dbbd...'
  ]
  },
  {
    id: 'keigokishi', name: 'テイネイキシ', en: 'Sir Courteous', area: 'grammar', hp: 5,
    msg: '「です・ます」で いうまで みちを あけない。',
    pal: { a: '#4A5470', b: '#8E9AB8', c: '#D8DEF0', d: '#C83A3A', e: '#F8D048' },
    px: [
      '.........dddddd.........',
      '........dddddddd........',
      '........dddddddd........',
      '.......dddddddddd.......',
      '.....ddaaaaaaaaaadd.....',
      '....daaaaaaaaaaaaaad....',
      '....daabbbbbbbbbbaad....',
      '...daabbbbbbbbbbbbaad...',
      '...daabbbbbbbbbbbbaad...',
      '...daabbbbbbbbbbbbaad...',
      '...daaccccccccccccaad...',
      '...daaccccccccccccaad...',
      '...daabbbbbbbbbbbbaad...',
      '....daabbbbbbbbbbaad....',
      '.....daaaaaaaaaaaad.....',
      '...dddaaaaaaaaaaaaddd...',
      '.ddaaaabbbeeeebbbaaaadd.',
      'daaaabbbbbeeeebbbbbaaaad',
      'daaaabbbbbeeeebbbbbaaaad',
      'aaaabbbbbbbeebbbbbbbaaaa',
      'aaaabbbbbbbbbbbbbbbbaaaa',
      'daaaabbbbbbbbbbbbbbaaaad',
      'daaaaaddddddddddddaaaaad',
      '.ddaad............daadd.'
  ]
  },
  // ---- どこにでも出る ----
  {
    id: 'carelesskoumori', name: 'ケアレスコウモリ', en: 'Slipupbat', area: 'any', hp: 3,
    msg: 'わかったはずの もんだいを もちさる。',
    pal: { d: '#14142A', a: '#3A2E4E', b: '#6E5A8E', c: '#F0C830' },
    px: [
      '.daad..............daad.',
      '.daaad............daaad.',
      '.daaadd..........ddaaad.',
      '.daaaaad...dd...daaaaad.',
      '.daaaaad..daad..daaaaad.',
      'daaaaaaaddaaaaddaaaaaaad',
      'daaaaaaaaaaaaaaaaaaaaaad',
      'aaaaaaaaaaaaaaaaaaaaaaaa',
      'aaabbaaaccaaaaccaaabbaaa',
      'aabbbbbaccaaaaccaabbbbaa',
      'aabbbbbaaaaaaaaaaabbbbaa',
      'dabbbbbbaaaaaaaaabbbbbad',
      '.dbbbbbbaaaaaaaaabbbbbd.',
      '..dbbbbbaaaaaaaabbbbbd..',
      '..dbbbbbaaaaaaaabbbbbd..',
      '...ddbbaaaaaaaaaabbdd...',
      '.....daaaaaaaaaaaad.....',
      '......daaaaaaaaaad......',
      '......daaaaaaaaaad......',
      '.......daaaaaaaad.......',
      '.......daaaddaaad.......',
      '.......daad..daad.......',
      '........dd....dd........',
      '........................'
  ]
  },
  {
    id: 'nemukegumo', name: 'ネムケグモ', en: 'Snoozepider', area: 'any', hp: 4,
    msg: 'よる おそくに あらわれて、あたまを ぼんやりさせる。',
    pal: { a: '#2E2A3E', b: '#5A5470', c: '#C83A5A', d: '#8E88A8' },
    px: [
      'ddd..................ddd',
      'dddd................dddd',
      'ddddd..............ddddd',
      '.ddddd..dd....dd..ddddd.',
      '..ddddddddd..ddddddddd..',
      '...dddddddddddddddddd...',
      '....ddddddaaaadddddd....',
      '.....ddddaaaaaadddd.....',
      '...ddddaaaaaaaaaadddd...',
      '..dddaaaaaaaaaaaaaaddd..',
      '.ddddaaaabbbbbbaaaadddd.',
      'dddaaaabbbbbbbbbbaaaaddd',
      'dddaaaabccbbbbccbaaaaddd',
      'ddaaaabbccbbbbccbbaaaadd',
      'ddaaaabbbbbbbbbbbbaaaadd',
      '.daaaabbbbbbbbbbbbaaaad.',
      '.daaaabbbbbbbbbbbbaaaad.',
      '..daaaabbbbbbbbbbaaaad..',
      '..daaaabbbbbbbbbbaaaad..',
      '...daaaaabbbbbbaaaaad...',
      '...ddddaaaaaaaaaadddd...',
      '..dddddddaaaaaaddddddd..',
      '.ddddd..daaaaaad..ddddd.',
      '.dddd....ddaadd....dddd.'
  ]
  },
  // ---- ボス ----
  {
    id: 'moshinomaou', name: 'タメシノマオウ', en: 'Archfiend of Trials', area: 'boss', hp: 12,
    msg: 'ほんばんと おなじ すがたで、ちからを うつしだす。',
    pal: { a: '#4A1030', b: '#8E2050', c: '#E85A7A', d: '#F8D048' },
    px: [
      'daadd..............ddaad',
      'aaaaad............daaaaa',
      'aaaaadd..........ddaaaaa',
      'daaaaaad........daaaaaad',
      'daaaaaadd......ddaaaaaad',
      '.ddaaaaaaddddddaaaaaadd.',
      '...daaaaaaaaaaaaaaaad...',
      '...daaaaaaaaaaaaaaaad...',
      '.ddaabbbbbbbbbbbbbbaadd.',
      'daabbbbbbbbbbbbbbbbbbaad',
      'daabbbddbbbbbbbbddbbbaad',
      'aabbbbddbbbbbbbbddbbbbaa',
      'aabbbbbbbbbbbbbbbbbbbbaa',
      'aabbbbbbbbbbbbbbbbbbbbaa',
      'aabbbbccccccccccccbbbbaa',
      'daabbbccccccccccccbbbaad',
      '.dabbbbccccccccccbbbbad.',
      '.daabbbbbccccccbbbbbaad.',
      'daaabbbbbbbbbbbbbbbbaaad',
      'aaaabbbbbbbbbbbbbbbbaaaa',
      'aaaaddaaaaaaaaaaaaddaaaa',
      'daaad.daaaaaaaaaad.daaad',
      'daaad.daaaaddaaaad.daaad',
      '.daad..daad..daad..daad.'
  ]
  }
];
